name: 05 Checkout Example

on:
  workflow_dispatch:

jobs:
  demo-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List space
        run: ls -al ${{ github.workspace }}

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: List space again
        run: ls -al ${{ github.workspace }}

