name: 06 Passing Data Between Steps

on:
  workflow_dispatch:

jobs:
  data-passing:
    runs-on: ubuntu-22.04
    steps:
      - name: Create data
        id: sender
        run: |
          echo "name=Mark" >> $GITHUB_OUTPUT

      - name: Receive data
        run: |
          echo ${{ steps.sender.outputs.name }}

