name: 07 Passing Files in Artifacts

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install tox
        run: pip install tox
        
      - name: Run unit tests
        run: |
          cd backend
          tox -e unit
          ls -al ${{ github.workspace }}/backend
          echo "Any coverage files?"
          ls -al ${{ github.workspace }}/backend/.coverage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ${{ github.workspace }}/backend/.coverage

  load-file-example:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ${{ github.workspace }}

      - name: List folder
        run: ls -al ${{ github.workspace }}


