name: 17 Docker Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Custom Action
        uses: mock/docker-action@0.1.0
        with:
          name: 'John'
        id: custom-action

      - name: Print Processed Name
        run: |
          echo "Processed Name: ${{ steps.custom-action.outputs.processed-name }}"
          echo "workdir"
          ls -la

